### ISSUE TITLE
Contacting you regarding nsxiv

### ISSUE THREAD

**Issue by WitherCubes** [mamg22/dotfiles#1]
I don't know if you know about this or not but nsxiv's development has switched to [codeberg](https://codeberg.org/nsxiv/nsxiv) because of [this incident](https://codeberg.org/nsxiv/nsxiv-tmp/issues/1).

One more thing. nsxiv has updated to v30 and all links in the fedora copr repo you are managing should be changed to the codeberg repo links.

I am making a issue in here because I don't know any other way of contacting you.

Thank You

*(P.S: Excuse me for my bad grammar)*

**Comment by mamg22** [comment]
Hi, thanks for letting me know. I've been aware of the codeberg move by reading email notifications, though I haven't had enough time to keep up with that lately. I'll make sure to update the copr repo and checkout codeberg as soon I can get some time.

Again, thanks :-)
